---
# Defaults
# ========
#
# ..var:: string domain_name
#
#     Domain name for the CDN distribution. An ACM certificate *will*
#     be created for this domain, but DNS entries *will not* be created
#     for it
#
domain_name:

# ..var:: string validation_domain_name
#
#     The domain to use to validate the ACM certificate. Defaults to the
#     parent domain of ``domain_name``
#
validation_domain_name: "{{domain_name | regex_replace('^.*?\\.')}}"

# ..var:: string cdn_price_class
#
#    Price class for CloudFront. Must be *PriceClass_100*, *PriceClass_200* or
#    *PriceClass_All*, indicating how many CloudFront servers (and in which
#    locations) should be used.
#
#    See: http://aws.amazon.com/cloudfront/pricing/
#
cdn_price_class: PriceClass_100

# ..var:: list default_hpkp_pins
#
#     List of SHA256 fingerprints to pin via HPKP, excluding the current
#     leaf certificate.
#
#     NB. calculate these with:
#
# ..code-block:: bash
#
#     $ cat mycert.pem | \
#       openssl x509 -noout -pubkey | \
#       openssl asn1parse -noout -inform pem -out /tmp/hpkp.asn1 && \
#       openssl dgst -sha256 -binary /tmp/hpkp.asn1 | \
#       openssl enc -base64
#
default_hpkp_pins:
 - JSMzqOOrtyOT1kmau6zKhgT676hGgczD5VMdRMyJZFA=  # Amazon Server CA 1B
 - KwccWaCgrnaw6tsrrSO61FgLacNgG2MMLq8GE6+oP5I=  # Starfield G2

# ..var:: list hpkp_pins
#
#    List of additional SHA256 fingerprints for HPKP
#
hpkp_pins: []

# ..var:: string content_security_policy
#
#    Content-Security-Policy header value
#
content_security_policy: "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';"
