---
# Tasks
# =====
#
- name: Create an OAI for CloudFront
  cloudfront_oai:
    state: present
    comment: "{{aws_environment}}-oai"
  register: oai
  tags:
    - web-assets

- name: Create the ACM certificate (**MUST** be in us-east-1!)
  cloudformation:
    stack_name: "{{aws_environment}}-cert"
    state: present
    region: us-east-1
    template: roles/web-assets/files/cdn-cert.yml
    template_parameters:
      DomainName: "{{domain_name}}"
      ValidationDomainName: "{{validation_domain_name}}"
  register: cert_stack
  tags:
    - web-assets

- name: Create CDN distribution and associated resources
  cloudformation:
    stack_name: "{{aws_environment}}-cdn"
    state: present
    template: roles/web-assets/files/cdn-resources.yml
    template_parameters:
      Environment: "{{aws_environment}}"
      PriceClass: "{{cdn_price_class}}"
      OriginAccessIdentityId: "{{oai.identity.id}}"
      OriginAccessIdentityCanonicalUser: "{{oai.identity.s3_canonical_user_id}}"
      DomainName: "{{domain_name}}"
      Certificate: "{{cert_stack.stack_outputs.Certificate}}"
      HPKPHeader: "{{hpkp_header}}"
  register: cdn_stack
  tags:
    - web-assets

- name: Fix lambda run-time
  lambda:
    name: "{{cdn_stack.stack_outputs.CDNLambda}}"
    state: present
    runtime: "nodejs4.3-edge"
  tags:
    - web-assets

- name: Associate the Lambda with the CloudFront distribution (+ fix IPv6)
  cloudfront_misc:
    id: "{{cdn_stack.stack_outputs.CDNId}}"
    is_ipv6_enabled: true
    lambda_assoc_eventtype: viewer-response
    lambda_assoc_arn: "{{cdn_stack.stack_outputs.CDNLambda}}"
  tags:
    - web-assets

- include: tests.yml
  tags:
    - web-assets
    - tests
