---
# Tasks
# =====
#
- name: Create an OAI for CloudFront
  cloudfront_oai:
    state: present
    comment: "{{aws_environment}}-oai"
  register: oai
  tags:
    - web-assets

- name: Create CDN distribution and associated resources
  cloudformation:
    stack_name: "{{aws_environment}}-cdn"
    state: present
    template: roles/web-assets/files/cdn-resources.yml
    template_parameters:
      Environment: "{{aws_environment}}"
      PriceClass: "{{cdn_price_class}}"
      OriginAccessIdentityId: "{{oai.identity.id}}"
      OriginAccessIdentityCanonicalUser: "{{oai.identity.s3_canonical_user_id}}"
      HPKPHeader: "{{hpkp_header}}"
  register: cdn_stack
  tags:
    - web-assets

- name: Fix lambda run-time
  lambda:
    name: "{{cdn_stack.stack_outputs.CDNLambda}}"
    state: present
    runtime: "nodejs4.3-edge"
  tags:
    - web-assets

- include: tests.yml
  tags:
    - web-assets
    - tests
